name: Khcraft
version: ${project.version}
main: org.kh.khcraft.Khcraft
api-version: 1.16
commands:
  mining:
    description: Used to select/upgrade/disable mining related enchantments
    usage: Incorrect syntax! /mining <select/upgrade/disable> <tool name> <enchantment name (if upgrade/select)> <level (if select)>
  digging:
    description: Used to select/upgrade/disable digging related enchantments
    usage: Incorrect syntax! /digging <select/upgrade/disable> <tool name> <enchantment name (if upgrade/select)> <level (if select)>
  chopping:
    description: Used to select/upgrade/disable chopping related enchantments
    usage: Incorrect syntax! /chopping <select/upgrade/disable> <tool name> <enchantment name (if upgrade/select)> <level (if select)>
  farming:
    description: Used to select/upgrade/disable farming related enchantments
    usage: Incorrect syntax! /farming <select/upgrade/disable> <tool name> <enchantment name (if upgrade/select)> <level (if select)>
  fishing:
    description: Used to select/upgrade/disable fishing related enchantments
    usage: Incorrect syntax! /fishing <select/upgrade/disable> <tool name> <enchantment name (if upgrade/select)> <level (if select)>
  combat:
    description: Used to select/upgrade/disable combat related enchantments
    usage: Incorrect syntax! /combat <select/upgrade/disable> <tool name> <enchantment name (if upgrade/select)> <level (if select)>
  archery:
    description: Used to select/upgrade/disable archery related enchantments
    usage: Incorrect syntax! /archery <select/upgrade/disable> <tool name> <enchantment name (if upgrade/select)> <level (if select)>
  trident:
    description: Used to select/upgrade/disable trident related enchantments
    usage: Incorrect syntax! /trident <select/upgrade/disable> <tool name> <enchantment name (if upgrade/select)> <level (if select)>
  general:
    description: Used to select/upgrade/disable general enchantments
    usage: Incorrect syntax! /general <select/upgrade/disable> <tool name> <enchantment name (if upgrade/select)> <level (if select)>
  skills:
    description: Displays all skill levels, experience, and available points
    usage: Just type /skills
  trade:
    description: User to trade KenBucks with other players
    usage: Incorrect syntax! /trade <player name> <amount> <message (optional)>
  balance:
    aliases: [kb]
    description: Displays a player's balance
    usage: Type /balance to display your own, or /balance <player name> to see another person's balance
  shop:
    description: Lists the items available for purchase on the server store
    usage: Just type /shop
  buy:
    description: Used to purchase items from the server store
    usage: Incorrect syntax! /buy <item name>